name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set Environment Variables
      run: |
        echo "DB_URL=jdbc:mysql://34.72.131.182:3306/school" >> $GITHUB_ENV
        echo "DB_USERNAME=root" >> $GITHUB_ENV
        echo "DB_PASSWORD=150030441@klU" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B package --file NewSMS/pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
